// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnoybkbpnclxduypmsrt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhub3lia2JwbmNseGR1eXBtc3J0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0ODQ4MjIsImV4cCI6MjA2ODA2MDgyMn0.vXLtu6N6Axkk-276t_v4EwpyiLaLECfXgpkIIwXVjVU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});